---
ami_id: 'ami-c82804ab' # AMI ID to build from, accepted as command line param
ec2_key_name: devcon-temp #temporary key to use to decrypt the local admin password. gets deleted after deployment
ec2_instance_size: 't2.medium' # AWS instance type to deploy, accepted as command line param
ec2_instance_tags: {App: devcon2016_v1} # Tag that gets applied to new instances
ec2_instance_tags_old: {App: devcon2016} # EC2 instances with this tag will be deleted
instances_count: 1 # number of instances to deploy, accepted as command line param
vpc_subnet_id: subnet-9856a2ee # name of VPC subnet to put instances in to
security_group: sg-56622d32 # name of security group to apply to new instances
awsregion: ap-southeast-2 # name of AWS Region to deploy new instances to
awsbucket: dobrien-dev # name of S3 bucket
awsbucketfolderpath: devcon2016 # name of folder in S3 bucket
devcon2016_iam_role: packer-windows # name of IAM role applied to DevCon2016 instances
enable_monitoring: yes # specify if EC2 monitoring should be enabled
ec2_data_disk_size: 500 # size in GB of data disk on EC2 instances
azure_automation_node_config: 'trivialweb.isvbox'
aa_registrationkey: 'l1+yBCsj09DuHhR7CofZpbBZVi12TetENk/uE/Rw9SopFDtQCZc+cRlTWiIffChZvddnjnVSXbxcxXblUpJ9ow=='
route53_zone: versent-innovation.com.au
route53_name: devcon2016
elb_name: devcon2016