---
- name: Include the default vars from the devcon2016 roles
  include_vars: roles/devcon2016/defaults/main.yml

- name: Wait for 5 minutes to give user_data script a chance to complete
  pause:
    minutes: 5

- name: Copy new index.html to web server
  win_template:
    src: roles/devcon2016/templates/index.html.j2
    dest: 'C:\\inetpub\\wwwroot\\index.html'

- name: Copy AA DSC template to remote node
  win_template:
    src: roles/devcon2016/templates/configure_dsc.ps1.j2
    dest: 'C:\\Windows\temp\configure_dsc.ps1'

- name: Onboard node to Azure Automation DSC
  raw: 'powershell.exe -ExecutionPolicy Bypass -File C:\\Windows\temp\configure_dsc.ps1'

- name: Remove temporary s3downloads folder
  win_file:
    path: "C:\\s3downloads"
    state: absent